### PR TITLE
Update to 1.20.6

### LINKED ISSUE #216: 1.20.6 Support

### PR DESCRIPTION
**Pull request by UltimatChamp**
## TODO
- `spruceui` -> `5.0.4`
  - _waiting for https://github.com/LambdAurora/SpruceUI/pull/52 or similar to get updated!_
  - The config system works flawlessly when using a local build of the SpruceUI port!

## TL;DR
- Updated to 1.20.6! _(fixes https://github.com/LambdAurora/LambDynamicLights/issues/216)_ 
- Using Java `21`, including the GitHub workflow!
- Updated dependencies!

* * *

#### For those who can't wait ;) :
- _https://github.com/UltimatChamp/LambDynamicLights/actions/runs/9092830965/artifacts/1504349432_
- _https://github.com/Natan822/SpruceUI/actions/runs/9071154568/artifacts/1499098405 (for mod menu config screen to work)_

### CODE REVIEW

**Comment by TechySC23** [comment]
@LambdAurora Please merge this PR quickly and ASAP. WE NEED THE **1.20.6** VERSION **ATLEAST**

**Comment by UltimatChamp** [comment]
#227

**Comment by Sarven432** [comment]
Links say "Failed to generate URL to download artifact."

**Comment by ghost** [comment]
> Links say "Failed to generate URL to download artifact."

GitHub artifacts expire. If you’re really that desperate you can do research on how to pull the mod, and build it yourself

**Comment by Gio-glitch04** [comment]
Hi! Can you please update the links? I need this mod to use it with block_displays

**Pull request closed without merging**
