### PR TITLE
bump: Update to Minecraft 1.19.4 (#144).

### PR DESCRIPTION
**Pull request by 5HT2**
I also bumped `fabric` and `fabricloader` in the Fabric mod dependencies, I wasn't sure what was reasonable so I went with what the [fabricmc.net/develop](https://fabricmc.net/develop/) site gives you.

Please let me know if I should downgrade either of those at all.

### CODE REVIEW

**Comment by LambdAurora** [comment]
For the versions, as long as they're versions supported by Quilt I'm fine.

**Comment by AuroraDoesCode** [comment]
I did a quick compile to test, seems to work fine on quilt for 1.19.4.

**Comment by 5HT2** [comment]
Confirmed, yes, it does! I'll make another pr to add a `runClientQuilt` to make testing on Quilt easier.

**Comment by 5HT2** [comment]
@LambdAurora anything else you need me to do for this PR / anything I should change?

**Comment by lucasjpf** [comment]
uptade to 1.20

**Comment by 5HT2** [comment]
> uptade to 1.20

what? #156

**Pull request merged**
