### PR TITLE
1.20.4 support

### LINKED ISSUE #200: 1.20.3/4 Support
**Is your feature request related to a problem? Please describe.**
As many are you are likely aware, 1.20.3/4 just released. Unfortunately, this mod fails to load on the latest iteration of Minecraft.

**Describe the solution you'd like**
1.20.3/4 Support Compatibility

**Describe alternatives you've considered**
Potential Fork/PR from a contributor.

**Additional context**
Thank you for your hard work and dedication towards keeping this mod compatible with the latest versions of Minecraft. Your work doesn't go unnoticed and am very impressed with all of the efforts you've committed so far!

### LINKED ISSUE #204: Minecraft keeps crashing
so when i open minecraft its fine on the title screen but when i open an world it first autosaves and then crashes

**To Reproduce**
i actually have no idea it just crashes

**Expected behavior**
i expected my world to open normally

**Desktop (please complete the following information):**
 - OS: [Windows 10 home]
 - Minecraft [1.20.4]
 - Fabric Loader version [ 0.15.3+build:idk]
 - Mods [i have 113 so i cant write them here]
 - Version [WHAT VERSION!?!]
 - Branch [whats a branch]

### PR DESCRIPTION
**Pull request by joestr**
**Changes:**
- Bump dependencies
- Modify method  Mixin signature in `WorldMixin.java` at `onBlockEntityTick` to match new method signature [BlockEntityTickInvoker](https://maven.fabricmc.net/docs/yarn-20w51a+build.9/net/minecraft/world/chunk/BlockEntityTickInvoker.html)

Fixes #200
Fixes #204 

*Note: I'm fairly new to the client modding scene. I only tested the lighting part.*

### CODE REVIEW

**Comment by Kichura** [comment]
Despite lighting being about the same as the one in 1.20.2, PR seems to be functioning properly including all GUI pages.

*edit: the GUI however seems to be super dark in terms of transparency, unsure if that was intentional.*

**Comment by joestr** [comment]
> edit: the GUI however seems to be super dark in terms of transparency, unsure if that was intentional.

I think this is from the SpruceUI library.

**Comment by TreyRuffy** [comment]
PR seems to work well in 1.20.4!

**Comment by ajamesmichaels** [comment]
I was also able to build from this branch and run in 1.20.4!

**Review by tocram1 — APPROVED** [review]

**Comment by joestr** [comment]
Fixes #204

**Comment by amyipdev** [comment]
Works flawlessly on 1.20.4

**Comment by DovydasTEDS** [comment]
if possible can a maintainer approve the workflow so that the branch could be merged?

**Comment by DovydasTEDS** [comment]
@LambdAurora Can you merge this?

**Comment by KAGUYA-1137** [comment]
**It doesn't seem to work if indium is installed**

**Comment by SA64BD** [comment]
Thanksss!

**Comment by cptlobster** [comment]
> **It doesn't seem to work if indium is installed**

I didn't have any issues with indium when I tried it. What exactly isn't working? Does the game launch, can you open a world without it crashing, is the dynamic lighting just not working in-game?

**Comment by KAGUYA-1137** [comment]
> > **インジウムが取り付けられていると動作しないようです**
> 
> 試してみたところ、インジウムに問題はありませんでした。具体的に何がうまくいっていないのでしょうか?ゲームが起動し、クラッシュせずに世界を開くことができますか、動的ライティングがゲーム内で機能していませんか?

**It's not that Indium doesn't work, but that LambDynamicLights almost doesn't work if Indium is installed.**
The reason I say almost is because non-solid blocks such as tall grass were affected by LambDynamicLights, but solid blocks such as stone and deepslate were not affected by LambDynamicLights.

I'm Japanese so I used Google Translate, sorry for the bad English.

**Pull request merged**
